#!/usr/local/bin/bash

#
# This program will make sure that the rstunnel process is constantly running. 
# Which means that you dont have to run rstunnel in a cron format.  
#


#
# First grabbing all the variable from the rstunnel.conf file.
#

if [ ! -x rstunnel.conf ]; then
        echo "[FATAL] Can't find rstunnel.conf. Run install.sh to generate rstunnel.conf";
        exit 1
else
        . rstunnel.conf
fi


#
# Setting the counter variables
#
counter=1
last_count=$seconds
	

trap "exit" 15

while [ true ]; do

	while [ $counter -lt $last_count ]; do
		let counter=$counter+1
		sleep 1
		if [ $counter = $last_count ]; then
			counter=1
			sleep 2
			echo `date`" "`hostname`": Rstunneld" >> $logfile
			./${rstunnel_bin} >> $logfile
		fi
	done 		

done
